---
title: "Dataset analysis code"
author: "Venus and Michelle"
date: "February 5, 2017"
output: html_document
---
## Set working directory ##

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("C:/Users/Venus/Github/QB2017BenavidezKuo/data")
```

## Loading packages ## 

```{r}

package.list <- c('vegan', 'ade4', 'viridis', 'gplots', 'BiodiversityR', 'indicspecies', 'tidyr', 'dplyr') 
for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) { 
    install.packages(package)
    library(package, character.only=T)
} }
```

## Load and transform datasets ## 

```{r pressure}
setwd("C:/Users/Venus/Github/QB2017BenavidezKuo/data")
# Load BCI datasets # 
BCI2010 <- read.delim("BCI2010.txt", header=T)
BCI2005 <- read.delim("BCI2005.txt", header=T)
BCI2000 <- read.delim("BCI2000.txt", header=T)
BCI1995 <- read.delim("BCI1995.txt", header=T)
BCI1990 <- read.delim("BCI1990.txt", header=T)
BCI1985 <- read.delim("BCI1985.txt", header=T)
BCI1982 <- read.delim("BCI1982.txt", header=T)

# Formatting datasets into SbyS matrcies # 
BCI.2010.SbyS <- group_by(BCI2010, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.2005.SbyS <- group_by(BCI2005, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.2000.SbyS <- group_by(BCI2000, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.1995.SbyS <- group_by(BCI1995, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.1990.SbyS <- group_by(BCI1990, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.1985.SbyS <- group_by(BCI1985, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)
BCI.1982.SbyS <- group_by(BCI1982, Quadrat) %>% count(Latin) %>% spread(key=Latin, value=n , fill=0)

# Removing quadrat row
BCI.1982.SBS=BCI.1982.SbyS[,2:307]
BCI.1985.SBS=BCI.1985.SbyS[,2:308]
BCI.1990.SBS=BCI.1990.SbyS[,2:306]
BCI.1995.SBS=BCI.1995.SbyS[,2:304]
BCI.2000.SBS=BCI.2000.SbyS[,2:303]
BCI.2005.SBS=BCI.2005.SbyS[,2:300]
BCI.2010.SBS=BCI.2010.SbyS[,2:298]
```

## Alpha diversity ## 

```{r}


```

## Beta diversity ## 
PCA using log-transformed % cover estimates to determine how plots changed in species composition from 1982 to 2010  

```{r}
# PCoA
BCI.2010.db=vegdist(BCI.2010.SbyS,method="bray")
BCI.2010.pcoa=cmdscale(BCI.2010.db,eig=T,k=3)
explainvar1 <- round(BCI.2010.pcoa$eig[1] / sum(BCI.2010.pcoa$eig), 3) * 100
explainvar2 <- round(BCI.2010.pcoa$eig[2] / sum(BCI.2010.pcoa$eig), 3) * 100
explainvar3 <- round(BCI.2010.pcoa$eig[3] / sum(BCI.2010.pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)
par(mar = c(5, 5, 1, 2) + 0.1)
plot(BCI.2010.pcoa$points[ ,1], BCI.2010.pcoa$points[ ,2], ylim = c(-0.2, 0.3),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(BCI.2010.pcoa$points[ ,1], BCI.2010.pcoa$points[ ,2],
       pch = 19, cex = 3, bg = "gray", col = "gray")
text(BCI.2010.pcoa$points[ ,1], BCI.2010.pcoa$points[ ,2],
     labels = row.names(BCI.2010.pcoa$points))



BCI.1982.db=vegdist(BCI.1982.SbyS,method="bray")
BCI.1982.pcoa=cmdscale(BCI.1982.db,eig=T,k=3)
explainvar1 <- round(BCI.1982.pcoa$eig[1] / sum(BCI.1982.pcoa$eig), 3) * 100
explainvar2 <- round(BCI.1982.pcoa$eig[2] / sum(BCI.1982.pcoa$eig), 3) * 100
explainvar3 <- round(BCI.1982.pcoa$eig[3] / sum(BCI.1982.pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)
par(mar = c(5, 5, 1, 2) + 0.1)
plot(BCI.1982.pcoa$points[ ,1], BCI.1982.pcoa$points[ ,2], ylim = c(-0.2, 0.3),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(BCI.1982.pcoa$points[ ,1], BCI.1982.pcoa$points[ ,2],
       pch = 19, cex = 3, bg = "gray", col = "gray")
text(BCI.1982.pcoa$points[ ,1], BCI.1982.pcoa$points[ ,2],
     labels = row.names(BCI.1982.pcoa$points))


treeREL <- BCI.1982.SBS 
  for(i in 1:nrow(BCI.1982.SBS)) {
    treeREL[i, ] = BCI.1982.SBS[i, ] / sum(BCI.1982.SBS[i, ])
  }

tree.pcoa <- add.spec.scores(BCI.1982.pcoa, treeREL, method = "pcoa.scores")
text(BCI.1982.pcoa$cproj[ ,1], BCI.1982.pcoa$cproj[ ,2], 
     labels = row.names(BCI.1982.pcoa$cproj), col = "black")

```


```{r}
# Resemblance matrix # 
tree.dj <- vegdist(BCI.1982.SBS, method = "jaccard", binary = TRUE)
tree.db <- vegdist(BCI.1982.SBS, method = "bray")
tree.ds <- vegdist(BCI.1982.SBS, method = "bray", binary = TRUE)

tree.db

tree.db <- vegdist(BCI.1982.SBS, method = "bray", upper = TRUE, diag = TRUE)

order <- rev(attr(BCI.1982.db, "Sites"))

levelplot(as.matrix(tree.db), aspect = "iso", col.regions = inferno, 
          xlab = "Site", ylab = "Site", scales= list(cex=0.5),
          main= "BCI 1982 census year")

tree.ward <- hclust(tree.db, method = "ward.D2")

par(mar = c(1,5,2,2) + 0.1)
plot(tree.ward, main = "BCI 1982 Census Dataset", ylab = "Squared Bray-Curtis Distance")

```

## Ordination NMDS ##

```{r}
NMDS1982=metaMDS(BCI.1982.SBS,k=3,trymax=100)
NMDS2010=metaMDS(BCI.2010.SBS,k=3,trymax=100)

par(mfrow=c(1,2))
stressplot(NMDS1982)
ordiplot(NMDS1982,type="n")
orditorp(NMDS1982,display="species",col="red",air=0.01)
orditorp(NMDS1982,display="sites",cex=1.25,air=0.01)

par(mfrow=c(1,2))
stressplot(NMDS2010)
ordiplot(NMDS2010,type="n")
orditorp(NMDS2010,display="species",col="red",air=0.01)
orditorp(NMDS2010,display="sites",cex=1.25,air=0.01)
```


## Spatial distribution ## 

```{r}
ssad <- function(x){
  ad <- c(2, 2)
  ad <- BCI.1982.SbyS[, species]
  ad = as.vector(t(x = ad)) 
  ad = ad[ad > 0]
}
# 2. Set plot parameters
par(mfrow=c(2, 2))
# 3. Declare a counter variable
ct <- 0 # a counter variable
while (ct < 6){ 
  species <- sample(1:length(BCI.1982.SbyS), 1) 
  ad <- ssad(species) 
# 4. Write a while loop to plot the SSADs of six species chosen at random 
if (length(ad) > 2 & sum(ad > 10)) {
  ct <- ct + 1 
  plot(density(ad), col = 'red' , xlab = 'Site abundance' , 
       ylab = 'Probability Density')
  }
}

```

# Species-area relationship #

```{r}

lim <- 10
S.list <- c()
A.list <- c()

S.list <- c(S.list, Log10(S))
A.list <- c(A.list, log10(lim^2))
lim <- lim*2 
# 3. Be sure to log10-transform the richness and area data
# Plot SAR # 
results <- lm(S.list ~ A.list)

plot(A.list, S.list, col="dark red", pch=20, cex=2,
     main="Species-area relationship", 
     xlab="ln(Area)", ylab="ln(Richness)")

abline(results, col="red", lwd=2)

int <- round(results[[1]][[1]],2)
z <- round(results[[1]][[2]],2)
legend(x=2, y=2, paste(c('slope = ', z), collapse = " "), cex=0.8,
       box.lty=0)


```















