---
title: "Untitled"
author: "Venus"
date: "February 16, 2017"
output: html_document
---
## Setup work enviroment ##

```{r}
## Setup work enviroment ##
rm(list = ls())
setwd("C:/Users/Venus/Github/QB2017BenavidezKuo/data")
## Load packages ##
require("vegan")  
require("tidyr")
require("dplyr")
require("dixon")
```

## Load dataset ##

```{r}
setwd("C:/Users/Venus/Github/QB2017BenavidezKuo/data")
# From BCI, Panama from year 2000 #
BCI <- read.delim("BCI2010.txt", header=T)
# Slim down BCI data frame #
BCI.df <- subset(BCI, select = c(No., Latin, Quadrat, PX, PY))


```


```{r}
BCI.df.r <- subset(BCI, select = c(PX, PY, Latin))
ilist.r <- BCI.df.r[sample(nrow(BCI.df.r), size = 250, replace = FALSE), ]
colnames(ilist.r) <- c("x", "y", "sp")

# Use dixon package # 
dixon(ilist.r, nsim = 99, fortran = FALSE)

```

## Using for loop ## 
# For loop to randomly sample quadrat in BCI.dat #

```{r}
# For loop to randomly sample x indivudals in BCI dataframe #
# Define intermediate data frame to populate in for loop # 
neighbor.df <- data.frame()
# Define randomly x individuals from BCI #
ilist <- BCI.df[sample(nrow(BCI.df), size = 1000, replace = FALSE), ]
# Define number of individuals sampled in ilist and total individuals in BCI # 
ilist.rows <- nrow(ilist)
# For loop begins #
# For every individual in ilist, find the PX, PY, Latin, and No. to put into individual df #
for(i in 1:ilist.rows) {   
  x1 <- as.numeric(ilist[i,]["PX"])
  y1 <- as.numeric(ilist[i,]["PY"])
  sp1 <- ilist[i,]["Latin"]
  No <- ilist[i,]["No."]
  quad <- as.numeric(ilist[i,]["Quadrat"])
  #individual <- cbind(No, sp1, quad, x1, y1)

  # Define temporary df for all neighbors in each ilist individual # 
  temp.neighbor.df <- data.frame()
  
  # Subset that particular quadrat # 
  Q = subset(BCI.df, Quadrat == quad)
  # Set the number of individuals in that quadrat # 
  Q.rows <- nrow(Q)
  # Inner For loop begins # 
  # For each indiviudal in quadrat, find the distance between ilist individuals to quadrat individuals#
      for(j in 1:Q.rows) {
        x2 <- as.numeric(Q[j,]["PX"])
        y2 <- as.numeric(Q[j,]["PY"])
        sp2 <- Q[j,]["Latin"]
        No2 <- Q[j,]["No."]
        dist <- sqrt(((x1-x2)^2)+((y1-y2)^2))
        neighbor <- cbind(sp1, No, sp2, No2, x2, y2, dist)
        
        # Put all neighbors for each invidual into temp.neighbor.df # 
        temp.neighbor.df <- rbind(temp.neighbor.df, neighbor)
  
    }
        
  # Order neighbors by closest distance #
  temp.neighbor.df <- temp.neighbor.df[order(temp.neighbor.df$dist),]
  
  # The four closest neighbors and of each sampled indivudal put into neighbor.df # 
  neighbor.df <- rbind(neighbor.df, temp.neighbor.df[2:5, -c(5:7)])     
  
}

```


# Removing redundancy #

``` {r}
# Rename column #
colnames(neighbor.df) <- c("Individual", "Individual No.", "Neighbors", "Neighbors No.")

# Removing combinatorial redundancy in neighbor.df #
# Take Individual and Neighbors species name combination in alphabetical order then n1-n2=n # 
onesided.count.Q.df <- data.frame(t(apply(neighbor.df,1,sort)))
onesided.count.Q.df <- onesided.count.Q.df[!duplicated(onesided.count.Q.df),]

# Reorder dataframe # 
onesided.count.Q.df <- onesided.count.Q.df[,-c(1:2)]
colnames(onesided.count.Q.df) <- c("Individual", "Neighbors")
#onesided.count.Q.df <- onesided.count.Q.df[c(2,3,1)]

# Making count dataframe table based on neighbor.df #
#count.df <- group_by(neighbor.df, Individual) %>% count(Neighbors)
count.Q.df <- group_by(onesided.count.Q.df, Individual) %>% count(Neighbors) # %>% spread(key=Neighbors, value=n, fill=0)
```

# Manually making squared species by species matrix # 

```{r}
# Make squared matrix for species #
length(unique(neighbor.df$Individual)) 
length(unique(neighbor.df$Neighbors)) 
x <- as.matrix(neighbor.df$Individual)
y <- as.matrix(neighbor.df$Neighbors)
z <- rbind(c(x,y))
zz <- t(z)
z <- t(unique(zz))
length(unique(zz)) 
squared <- matrix(0 , nrow = length(unique(zz)), ncol=length(unique(zz)))
row.names(squared) <- sort(unique(zz))
colnames(squared) <- sort(z)

```

# Generating Null model as metric for species co-occurances #








```{r}
# Define df to put all bootstrapping results # 
co.occur.df <- NA
# Define number of simulations # 
ct100 <- 2
# For loop begins #
# For every individual in ilist, find the PX, PY, Latin, and No. to put into individual df #
# Outter for loop to bootstrap null model xx times #
for(k in 1:ct100) {
  
  # Randomize all PX and PY values # 
  BCI.df.random <- transform(BCI.df, PX = sample(PX), PY=sample(PY))
  # Define intermediate data frame to populate in for loop # 
  neighbor.df.r <- data.frame()
  # Define randomly x individuals from BCI #
  ilist.r <- BCI.df.random[sample(nrow(BCI.df.random), size = 10, replace = TRUE), ]
  # Define number of individuals sampled in ilist and total individuals in BCI # 
  ilist.rows.r <- nrow(ilist.r)
  
    # Inner for loop to get information about randomly sampled individual #
    for(i in 1:ilist.rows.r) {   
      x1.r <- as.numeric(ilist.r[i,]["PX"])
      y1.r <- as.numeric(ilist.r[i,]["PY"])
      sp1.r <- ilist.r[i,]["Latin"]
      No.r <- ilist.r[i,]["No."]
      quad.r <- as.numeric(ilist.r[i,]["Quadrat"])

      # Define temporary df for all neighbors in each ilist individual # 
      temp.neighbor.df.r <- data.frame()
  
      # Subset that particular quadrat # 
      Q.r = subset(BCI.df.random, Quadrat == quad.r)
      # Set the number of individuals in that quadrat # 
      Q.rows.r <- nrow(Q.r)
        # Inner For loop to get four closest neighbors for each individual sampled # 
        for(j in 1:Q.rows.r) {
          x2.r <- as.numeric(Q.r[j,]["PX"])
          y2.r <- as.numeric(Q.r[j,]["PY"])
          sp2.r <- Q.r[j,]["Latin"]
          No2.r <- Q.r[j,]["No."]
          dist.r <- sqrt(((x1.r-x2.r)^2)+((y1.r-y2.r)^2))
          neighbor.r <- cbind(sp1.r, No.r, sp2.r, No2.r, x2.r, y2.r, dist.r)
        
          # Put all neighbors for each invidual into temp.neighbor.df # 
          temp.neighbor.df.r <- rbind(temp.neighbor.df.r, neighbor.r)
        }
        
      # Order neighbors by closest distance #
      temp.neighbor.df.r <- temp.neighbor.df.r[order(temp.neighbor.df.r$dist),]
      # The four closest neighbors and of each sampled indivudal put into neighbor.df # 
      neighbor.df.r <- rbind(neighbor.df.r, temp.neighbor.df.r[2:5, -c(5:7)])        
      

    }
  
        # Rename column #
        colnames(neighbor.df.r) <- c("Individual", "Individual No.", "Neighbors", "Neighbors No.")

        # Removing combinatorial redundancy in neighbor.df #
        # Take Individual and Neighbors species name combination in alphabetical order then n1-n2=n # 
        onesided.count.Q.df.r <- data.frame(t(apply(neighbor.df.r,1,sort)))
        onesided.count.Q.df.r <- onesided.count.Q.df.r[!duplicated(onesided.count.Q.df.r),]

        # Reorder dataframe # 
        onesided.count.Q.df.r <- onesided.count.Q.df.r[,-c(1:2)]
        colnames(onesided.count.Q.df.r) <- c("Individual", "Neighbors")
        #onesided.count.Q.df <- onesided.count.Q.df[c(2,3,1)]

        # Making count dataframe table based on neighbor.df #
        #count.df <- group_by(neighbor.df, Individual) %>% count(Neighbors)
        count.Q.df.r <- group_by(onesided.count.Q.df.r, Individual) %>% count(Neighbors) # %>% spread(key=Neighbors,         value=n, fill=0)
  
        co.occur.df <- cbind(co.occur.df, count.Q.df.r)

}
```


```{r}
# Rename column #
colnames(neighbor.df.r) <- c("Individual", "Individual No.", "Neighbors", "Neighbors No.")

# Removing combinatorial redundancy in neighbor.df #
# Take Individual and Neighbors species name combination in alphabetical order then n1-n2=n # 
onesided.count.Q.df.r <- data.frame(t(apply(neighbor.df.r,1,sort)))
onesided.count.Q.df.r <- onesided.count.Q.df.r[!duplicated(onesided.count.Q.df.r),]

# Reorder dataframe # 
onesided.count.Q.df.r <- onesided.count.Q.df.r[,-c(1:2)]
colnames(onesided.count.Q.df.r) <- c("Individual", "Neighbors")
#onesided.count.Q.df <- onesided.count.Q.df[c(2,3,1)]

# Making count dataframe table based on neighbor.df #
#count.df <- group_by(neighbor.df, Individual) %>% count(Neighbors)
count.Q.df.r <- group_by(onesided.count.Q.df.r, Individual) %>% count(Neighbors) # %>% spread(key=Neighbors, value=n, fill=0)
```

# Analyses of bootstrapped null model compared with empirical # 

```{r}



```


